In [9]:
import pandas as pd

data = {'Color': ['Red', 'Green', 'Blue', 'Red', 'Green']}
df = pd.DataFrame(data)
print(df)


   Color
0    Red
1  Green
2   Blue
3    Red
4  Green


In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Color_Label'] = le.fit_transform(df['Color'])
print(df)


   Color  Color_Label
0    Red            2
1  Green            1
2   Blue            0
3    Red            2
4  Green            1


In [7]:
df['Original_Color'] = le.inverse_transform(df['Color_Label'])
print(df)


   Color  Color_Label Original_Color
0    Red            2            Red
1  Green            1          Green
2   Blue            0           Blue
3    Red            2            Red
4  Green            1          Green


In [8]:
import pickle

# Save the encoder
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)


In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {'Color': ['Red', 'Green', 'Blue', 'Red']}
df = pd.DataFrame(data)

# Fit the label encoder
le = LabelEncoder()
df['Color_Label'] = le.fit_transform(df['Color'])


In [3]:
import pickle

# Save the encoder
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)


In [5]:
# Load the encoder
with open('label_encoder.pkl', 'rb') as file:
    loaded_le = pickle.load(file)


In [6]:
# Encode new data
new_data = ['Green', 'Blue']
encoded = loaded_le.transform(new_data)
print("Encoded:", encoded)

# Decode back
decoded = loaded_le.inverse_transform(encoded)
print("Decoded:", decoded)


Encoded: [1 0]
Decoded: ['Green' 'Blue']


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('framingham.csv')

In [3]:
df.shape

(4240, 16)

In [4]:
# Split the first 3000 records
df_3000 = df.iloc[:3000]

# Split the remaining 1240 records
df_1240 = df.iloc[3000:]


In [5]:
# Save the 3000-records DataFrame
df_3000.to_csv('framingham_3000.csv', index=False)

# Save the 1240-records DataFrame
df_1240.to_csv('framingham_1240.csv', index=False)


In [6]:
df1 = pd.read_csv("framingham_1240.csv")

In [8]:
df1.shape

(1240, 16)

In [7]:
df2 = pd.read_csv("framingham_3000.csv")

In [9]:
df2.shape

(3000, 16)

In [10]:
# Drop the target column (replace 'TenYearCHD' with your actual target column if different)
df1 = df1.drop(columns=['TenYearCHD'])
df2 = df2.drop(columns=['TenYearCHD'])

In [11]:

# Save the updated DataFrames back to CSV (overwrite or save as new files)
df2.to_csv('framingham_3000_notarget.csv', index=False)
df1.to_csv('framingham_1240_notarget.csv', index=False)

In [13]:
# Select numeric features to scale
features_to_scale = ['age', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose']
X = df[features_to_scale].copy()

In [14]:
from sklearn.preprocessing import StandardScaler
import pickle

# Dictionary to store scalers for each column
scalers = {}

# Scale each column separately and save the scalers
for column in X.columns:
    scaler = StandardScaler()  # You can replace with MinMaxScaler() if preferred
    X[column] = scaler.fit_transform(X[column].values.reshape(-1, 1))
    
    # Save the scaler for this column
    with open(f'{column}_scaler.pkl', 'wb') as f:
        pickle.dump(scaler, f)

# Display the scaled data
print(X.head())



        age   totChol     sysBP     diaBP       BMI  heartRate   glucose
0 -1.234283 -0.935261 -1.196267 -1.083027  0.286614   0.342735 -0.207240
1 -0.417664  0.298311 -0.515399 -0.159355  0.718054   1.590247 -0.248992
2 -0.184345  0.186168 -0.220356 -0.243325 -0.112959  -0.073103 -0.499501
3  1.332233 -0.262404  0.800946  1.016227  0.681284  -0.904778  0.878299
4 -0.417664  1.083311 -0.106878  0.092555 -0.662065   0.758572  0.126772


In [19]:
import pickle
import pandas as pd

# Load the Framingham dataset (assuming it's already loaded)
df = pd.read_csv('framingham.csv')

# 1. Load the scaler for 'age'
with open('age_scaler.pkl', 'rb') as f:
    age_scaler = pickle.load(f)

# 2. Scale the 'age' column (all values)
age_data = df[['age']]  # Select the 'age' column
scaled_age = age_scaler.transform(age_data)

# 3. Display the scaled 'age' data
print("Scaled age data:")
print(scaled_age)

# 4. Inverse transform the scaled data (to get back the original values)
original_age = age_scaler.inverse_transform(scaled_age)

# 5. Display the original (inverse transformed) 'age' data
print("\nOriginal age data (inverse transformed):")
print(original_age)






Scaled age data:
[[-1.23428297]
 [-0.41766419]
 [-0.18434454]
 ...
 [ 0.28229477]
 [-1.11762315]
 [-1.23428297]]

Original age data (inverse transformed):
[[39.]
 [46.]
 [48.]
 ...
 [52.]
 [40.]
 [39.]]


c:\Users\SreeKeerthiReddyThat\Desktop\clustering\venv\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [20]:
scaled_age

array([[-1.23428297],
       [-0.41766419],
       [-0.18434454],
       ...,
       [ 0.28229477],
       [-1.11762315],
       [-1.23428297]])

In [21]:
original_age

array([[39.],
       [46.],
       [48.],
       ...,
       [52.],
       [40.],
       [39.]])